### ISSUE TITLE
Business Engineering the Workday Integration

### ISSUE THREAD

**Issue by hmitsch** [mozilla-iam/iam-project-backlog#1]
**Agile Story:**
As dev team I want to take an informed decision on the Workday Mozillians.org integration in order to build sustainable, robust and cost-effective software.

**Jobs To Be Done Story:**
When working on the Workday Mozillians.org implementation I want to have a crystal clear understanding of the integration technology (API, file via SFTP, etc) so I can ship software fast.
 
**Acceptance criteria:**
* Options to interface with Workday were presented to DEV team for backlog refinement
* Interface contract is agreed with Nancy (People team)

**Comment by gdestuynder** [comment]
this is now tracked in https://github.com/mozilla-iam/iam-project-backlog/issues/173
I believe we'll open a new issue when this is worked on as the story has change a little (not much though, but just for clarity I'd rather we rewrite it)
