### ISSUE TITLE
SSO Dashboard Implement initial version of UI design

### ISSUE THREAD

**Issue by comzeradd** [mozilla-iam/iam-project-backlog#103]
Based on the [design work](https://github.com/mozilla/iam-project-backlog/issues/53), next step is its frontend implementation.

**Comment by mbransn** [comment]
Tracking issues from the [SSO Dashboard repo](https://github.com/mozilla-iam/sso-dashboard-configuration) for initial release:

- [x] User Menu [#42](https://github.com/mozilla-iam/sso-dashboard/issues/42)
- [x] Logo/Menu Alignment [#41](https://github.com/mozilla-iam/sso-dashboard/issues/41)

**Comment by andrewkrug** [comment]
Initial PR is in for this and deployed to sso.allizom.org

**Comment by andrewkrug** [comment]
@m-branson is that checklist representative of what we would consider "done" for this story?

**Comment by mbransn** [comment]
Those tasks are the most obvious blockers to an initial release. Full list @comzeradd should be referencing is at the end of this [ticket](https://github.com/mozilla/iam-project-backlog/issues/53). Will post the list here as well for clarity:

- [x] Dashboard UI is implemented with the UI shown here: http://bit.ly/2oOOyZF
  - [x] Mozilla branded header.
  - [x] Search bar w/active, focused and hover states.
  - [x] Menu with or without user image populated. If no user image available, simple user icon is default.
  - [x] Menu active state with users name and the ability to Log Out. (Notifications, Settings and Access Request need to be prioritized for later releases.)
  - [x] Footer providing links to Help Desk, Privacy and Legal information. (If we need futher UI for the presentation of this linked information, let's prioritize it.)
- [x] App block iconography is of good resolution and equally sized.
- [x] User sees a dashboard populated with all of the apps they have access to.
  - [x] Apps are organized alphabetically.
  - The Recently Used section is populated with up to 5 of the user's most accessed apps.
**Out of scope for initial release, [added to backlog](https://github.com/mozilla-iam/sso-dashboard/issues/92).**
- [x] App blocks have a hover state.
- [x] The All section has a background color to differentiate it from the Frequently Used section.
- [x] SSO Dashboard is responsive and functions in mobile viewports.
  - [x] App blocks reduce in size and are vertically scrollable.
  - [x] Hover states are disabled, but focused and active states are retained. (Exploration of pressed states and other mobile optimization can be prioritized for later release.)

**Comment by andrewkrug** [comment]
@m-branson can I check off any of these boxes yet?  Seems like we're getting close.

**Comment by mbransn** [comment]
Quite close! Just took a run through and checked off what I felt was 'done'.

**Comment by andrewkrug** [comment]
We are going SO fast it's great.  Thanks for the update.

**Comment by mbransn** [comment]
Looks like the 'Recently used' section is the only thing that didn't make it. 👍 @comzeradd @andrewkrug should we open a backlog issue for that future implentation?

**Comment by andrewkrug** [comment]
@m-branson please do.  This could take on a bunch of different forms but it's definitely a backlog feature.

**Comment by mbransn** [comment]
@andrewkrug [done](https://github.com/mozilla-iam/sso-dashboard/issues/92).

**Comment by aminalhazwani** [comment]
The icons are quite big and they make the page overflow even on big screen. I am wondering if it would be possible to increase the information density of the dashboard by reducing the size of this component. Also having a list instead of a grid would make the dashboard much easier to scan and read. 👋

**Comment by mbransn** [comment]
👋 @aminalhazwani thanks for the feedback, super appreciated! As this is the first iteration of the new dashboard, I'm sure we'll be refining as the weeks go on. (I too feel that the apps are a bit large at the moment, something I plan to work on with @comzeradd 😊)

Can you do us a favor and [add your feedback here](https://discourse.mozilla-community.org/c/iam/dashboard)? This is the Discourse home for feedback and discussion about the dashboard specifically. Posting here will help us keep it all organized and ensure that enhancement requests are heard from users! Thanks again. 👍
