### ISSUE TITLE
Move testrp from delegation endpoint to silent authentication for session management

### ISSUE THREAD

**Issue by gdestuynder** [mozilla-iam/iam-project-backlog#104]

**Comment by gdestuynder** [comment]
This is done:
https://github.com/mozilla-iam/testrp.security.allizom.org/commit/36711903d5be4ab66c6f8f645e7316ca56a6e5ec
https://github.com/pingidentity/lua-resty-openidc/pull/47

Set to review as pingidentity actually reviews the implementation for lua

**Comment by zandbelt** [comment]
see: https://github.com/pingidentity/lua-resty-openidc/pull/47#discussion_r112803377 for a question on this

**Comment by gdestuynder** [comment]
tihs has been merged thanks @zandbelt !
