### ISSUE TITLE
SSO Dashboard Fail Page

### ISSUE THREAD

**Issue by mbransn** [mozilla-iam/iam-project-backlog#106]
Design a fail page to be used for 404s and other errors.

Requests for a humorous page have been made by various IAM team members, recommendations welcome. 😄

**Comment by mbransn** [comment]
@andrewkrug @comzeradd thoughts on this fail page?

Using the [video](https://www.youtube.com/watch?v=Ybvwh0reiMU) @flamingspaz called out in the IAM channel, though we can utilize anything (vid/img/gif).

![fail-page](https://cloud.githubusercontent.com/assets/18686986/25413080/583e1740-29dc-11e7-9627-96b78d774da8.jpg)

**Comment by andrewkrug** [comment]
I love it.  Let's roll with it.

**Comment by mbransn** [comment]
Awesome, thanks @andrewkrug.

@comzeradd what do you need from me to get this implemented? A marked up version (padding/sizing/etc) and a mobile version?

**Comment by comzeradd** [comment]
@m-branson yes, that would help. Just to get the alignments/paddings right.

@andrewkrug I guess the 404 page won't require authentication, right? So we would only have the logo on the top bar.

**Comment by mbransn** [comment]
@comzeradd here's the desktop annotation to get you started, mobile will have to wait til tomorrow (though I'm planning to simply stack simplistically in smaller viewports).

Also, [play button icon](https://drive.google.com/open?id=0B0vmiicLLrGuTkZKMFg5bDhVMkE) is in the drive folder. 

**Styles:**

![fail-page-styles](https://cloud.githubusercontent.com/assets/18686986/25500798/3aaad87a-2b45-11e7-9493-4d2f37611f53.jpg)

**Sizing:**

![fail-page-sizing](https://cloud.githubusercontent.com/assets/18686986/25500802/3fc43d9c-2b45-11e7-9b95-835eb821e203.jpg)

**Spacing:**

![fail-page-spacing](https://cloud.githubusercontent.com/assets/18686986/25500817/4bbb72c8-2b45-11e7-9dcf-6153ad42892c.jpg)

**Grid Reference:**

![grid-reference](https://cloud.githubusercontent.com/assets/18686986/25500828/52960004-2b45-11e7-8c4f-041d5f0e6b70.png)

**Comment by mbransn** [comment]
> @andrewkrug I guess the 404 page won't require authentication, right? So we would only have the logo on the top bar.

If a user is logged in they will still be able to utilize their user menu though, correct?

**Comment by mbransn** [comment]
@comzeradd here is the mobile viewport version. Images are [here](https://drive.google.com/open?id=0B0vmiicLLrGuTnVwa3JPRU41U0U) as well.

**Overview:**

![m-fail-page](https://cloud.githubusercontent.com/assets/18686986/25550934/cfd77000-2c32-11e7-8582-41082485a238.png)

**Spacing:**

![m-fail-page-spacing](https://cloud.githubusercontent.com/assets/18686986/25550948/f57aa99e-2c32-11e7-92ee-25b8cdb24d11.png)


**Sizing:**

![m-fail-page-sizing](https://cloud.githubusercontent.com/assets/18686986/25550943/eef6b7b6-2c32-11e7-8a49-97d50d6d81c2.png)
