### ISSUE TITLE
Move box client from sso to "client" in auth0

### ISSUE THREAD

**Issue by gdestuynder** [mozilla-iam/iam-project-backlog#108]
edit: we actually did that before figuring out that clients were better than the sso integration because more configurable

we should ask auth0 if they can move box to clients for us during the next production upgrade. if they cant we'll have to recreate the client (and thus call box)

**Comment by andrewkrug** [comment]
I just approved this pull as soon as it's merged can close this issue.

**Comment by gdestuynder** [comment]
@jdow ^^^^^

**Comment by jdow** [comment]
I will work on this after we've turned down Okta. Probably next week

**Comment by gdestuynder** [comment]
@jdow
