### ISSUE TITLE
SSO Dashboard Log Out Success UI

### ISSUE THREAD

**Issue by mbransn** [mozilla-iam/iam-project-backlog#109]
This ask came out of this [issue](https://github.com/mozilla-iam/sso-dashboard/issues/61). Opening a separate issue to track progress.

- [x] Design log out success page for SSO Dashboard.
- [x] Design log in page for SSO Dashboard (Auth0 lock without sign up functionality).

**Comment by mbransn** [comment]
Went ahead and comp'd these. Let me know thoughts.

**Log out success screen:**

Includes a button to return to log in. @comzeradd this button would fill black on hover. 

![sso-logout](https://cloud.githubusercontent.com/assets/18686986/25363762/fce7e4b8-2911-11e7-93c5-353c71f6e432.jpg)

**Log in screen:** 

Auth0 lock within the Mozilla branded SSO header, sign up language removed. @comzeradd this button would fill #FABA00 (orange) on hover.

![sso-login](https://cloud.githubusercontent.com/assets/18686986/25363773/1da5992a-2912-11e7-814b-ae9fe6cd77f4.jpg)

**Comment by mbransn** [comment]
Updated these pages to no longer have the SSO app-bar header (as both will be hosted at Auth0).


![sso-login](https://cloud.githubusercontent.com/assets/18686986/25413229/9f9f4b94-29dd-11e7-883f-04d546f01420.jpg)

![sso-logout](https://cloud.githubusercontent.com/assets/18686986/25413234/a4f0e0d0-29dd-11e7-96a3-1a6ea4102e34.jpg)

**Comment by comzeradd** [comment]
From mozilla-iam/sso-dashboard/issues/61 I get that the logout page will live inside the dashboard app. @andrewkrug can you confirm?

**Comment by andrewkrug** [comment]
@comzeradd that's the easiest way to handle it I think.  Rather than having yet another redirect.

**Comment by mbransn** [comment]
@comzeradd @andrewkrug sounds good, thanks for clarifying. Restating 'outloud' to be sure I'm on the same page: 

- SSO dashboard log in is hosted at Auth0 Lock.
- SSO dashboard log out is hosted within the dashboard.

As for UI, I still feel we should design the log out success screen without the SSO app-bar header (most recent visuals posted). Outside of the logged in experience the app-bar serves no purpose and the log out screen provides all necessary user options.

**Comment by andrewkrug** [comment]
@comzeradd @m-branson Correct.  Regarding the above statement.

**Comment by comzeradd** [comment]
Implemented at [471eb0e](https://github.com/mozilla-iam/sso-dashboard/commit/09b7774bb32d201974988cceb75aa32d6471eb0e)

**Comment by mbransn** [comment]
This looks great @comzeradd 👍
