### ISSUE TITLE
Support access-proxy for APIs

### ISSUE THREAD

**Issue by gdestuynder** [mozilla-iam/iam-project-backlog#110]
There is a demand to provide auth0-managed API keys that front existing APIs.
This is possible in a setup such as the one documented here: https://auth0.com/blog/use-nginx-plus-and-auth0-to-authenticate-api-clients/

Requirements:
 - [ ] Create a testrp setup with an API protected by the access-proxy, document it on the testrp repository
 - [ ] Associate RP's custom API keys with `user_id`'s
 - [ ] Refuse API keys for users not a in certain group, or disabled users

Bonus (probably goes in a new card later on) - these allow to completely handle API keys for the service, which is more reliable as we do not need to associate keys with `user_id`'s externally:
 - [ ] Create a process to issue API keys on behalf of the service (or even, a service, if possible)
 - [ ] Create a process to expire and revoke any API keys automatically

**Comment by hmitsch** [comment]
@gdestuynder on the current prio of this story:
> only #110 might be prioritized if we get more demand for it

**Comment by gdestuynder** [comment]
havent had more demand for it yet

**Comment by gdestuynder** [comment]
there is now demand  - https://github.com/mozilla-services/foxsec/issues/288#issuecomment-300520569
