### ISSUE TITLE
Semi-automate new Auth0 client provisioning with ServiceNow (The Hub) workflow management

### ISSUE THREAD

**Issue by gdestuynder** [mozilla-iam/iam-project-backlog#111]
This is the task of automating the ServiceNow SSO form to become a 1-click approval for new auth0 client.
Workflow proposal:

1. Service owner visits https://mana.mozilla.org/wiki/display/SECURITY/SSO+Request+Form to inform themselves of the options, etc.
2. Service owner fills service now request as per above link
3. Request is created, Jabba or someone else/group of people ("person in charge") are ping'd for acknowledgement
4. Validation
 a. Person in charge validate all the data is correct and click accept/ack
**OR**
 b. Person in charge click deny/back
 c. Service owner gets notification + msg explaining what is wrong
 d. Service owner correct the data in ServiceNow
 e. We're back to step 4
5.  ServiceNow automatically create the client in Auth0 and sends the credentials to the Service owner

Requirements
- [ ] Service now integration code (EUS/Systems teams)
- [ ] Auth0 API Management client id, secret, with scope for client create (Infosec team)

**Comment by andrewkrug** [comment]
ServiceNow automatically create the client in Auth0 and sends the credentials to the Service owner -- e-mail option, s3 AND/OR credstash deposit ?

**Comment by gdestuynder** [comment]
Some use cases:
- I'm an AWS user and I just want to be able to pick up the information (I would vote credstash here, though we probably need more options depending on the service owner, for example FirefoxServices use sops/KMS)
- I'm using a Saas and I need to pass the info over (I would vote some ServiceNow mechanism if available, else fallback to email +gpg, but that's not prefered)

**Comment by gdestuynder** [comment]
We need a ServiceNow API key for this, but we're did not get it so far

**Comment by gdestuynder** [comment]
we still haven't received the API key, iceboxing
