### ISSUE TITLE
CIS=>LDAP Identity driver

### ISSUE THREAD

**Issue by hmitsch** [mozilla-iam/iam-project-backlog#115]
- [x] publish LDAP changes in S3 https://github.com/mozilla-iam/auth0-scripts/tree/master/LDAP/ldap2s3
- [ ] pickup changes / write LDAP CIS publisher
- [ ] Write LDAP CIS validator

**Comment by andrewkrug** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1388856 has also been updated with information on this issue.
