### ISSUE TITLE
Write user profile to stream (From Mozillians.org)

### ISSUE THREAD

**Issue by hmitsch** [mozilla-iam/iam-project-backlog#117]
Story conceived in Q2 OKR Grooming Session.

Size: M (3 days)

**Comment by andrewkrug** [comment]
Implemented in CIS Library but untested in cis_functions

**Comment by andrewkrug** [comment]
@hmitsch who will do the mozillian's part of this?  We are ready to move forward with integration of Mozillian's with the CIS.

**Comment by johngian** [comment]
Are CIS lambda functions to receive data?

**Comment by andrewkrug** [comment]
@johngian yes ready for testing.  @gdestuynder completed three successful end to end trials yesterday.  I'm writing a little bit of documentation on how to invoke them from inside of another app but if you're comfortable we can move forward now.

**Comment by johngian** [comment]
Here I implement the logic behind it: https://github.com/mozilla-iam/cis/pull/57
Publishing from mozillians.org is just a call of this method.

**Comment by hmitsch** [comment]
@andrewkrug sorry I had not answered, @johngian thanks for getting on board. 😄
