### ISSUE TITLE
Setup CI

### ISSUE THREAD

**Issue by hmitsch** [mozilla-iam/iam-project-backlog#120]
Story conceived in Q2 OKR Grooming Session.

Size: M (3 days)

**Comment by andrewkrug** [comment]
Currently blocked while we decide on IAM grants for devs.

**Comment by andrewkrug** [comment]
See: https://github.com/mozilla-iam/cis/issues/5

**Comment by andrewkrug** [comment]
No longer blocked but still needs done.
