### ISSUE TITLE
Run access-proxy in front of sso-dashboard for session support

### ISSUE THREAD

**Issue by gdestuynder** [mozilla-iam/iam-project-backlog#126]
See https://github.com/mozilla-iam/sso-dashboard/issues/107
Setting andrew as main assignee on this card, but  i'm also assigned on the sub card since i'll help with that as much as possible

**Comment by andrewkrug** [comment]
Code cleanup and refactor to prep for this: https://github.com/mozilla-iam/sso-dashboard/pull/127

**Comment by andrewkrug** [comment]
Blocked by https://github.com/mozilla/iam-project-backlog/issues/136

**Comment by andrewkrug** [comment]
Blocked by https://github.com/mozilla/iam-project-backlog/issues/137

**Comment by gdestuynder** [comment]
we currently don't really need this, iceboxed
