### ISSUE TITLE
IAM Category on Discourse

### ISSUE THREAD

**Issue by hmitsch** [mozilla-iam/iam-project-backlog#13]
Please create a discourse category/mailing list for the IAM project. Please add the members of the IAM project to it or share how to subscribe to it with the project members.

Please also email the iam-dev@mozilla mailing list indicating that the purpose of the list is changing and it will now be an open list for RPs to join. Tell IAM project members on the list they're welcome to stay but to please make sure to use the new discourse category for iam project discussion and reserve the iam-dev@mozilla list for communication with and between RPs.

**Comment by gene1wood** [comment]
@hmitsch Would you help with this by creating an IAM project user group in Mozillians and adding the members of the project to it so Leo can use that to create a discourse group?

**Comment by hmitsch** [comment]
@LeoMcA assigning this to you. Do you need any help?

**Comment by hmitsch** [comment]
Created group: https://mozillians.org/group/iam-project/

**Comment by LeoMcA** [comment]
Category created: https://discourse.mozilla-community.org/c/iam

And post sent to iam-dev: https://groups.google.com/a/mozilla.com/forum/#!topic/iam-dev/NnAO5cDlLvc
