### ISSUE TITLE
Log In UI Design

### ISSUE THREAD

**Issue by mbransn** [mozilla-iam/iam-project-backlog#135]
Design UI to align the Auth0 Lock with the new brand, SSO and [sign up](#125) experiences.

**Comment by gdestuynder** [comment]
See also https://projects.invisionapp.com/share/CSAFEROA6#/screens/218730609

**Comment by gdestuynder** [comment]
See also https://bugzilla.mozilla.org/show_bug.cgi?id=1320685

**Comment by gdestuynder** [comment]
NLX definitely has this :)
