### ISSUE TITLE
Create ansible role to deploy access proxy and publish publicly.

### ISSUE THREAD

**Issue by andrewkrug** [mozilla-iam/iam-project-backlog#136]
In order to complete the task of moving the sso-dashboard to using the access proxy we will need an ansible role that stands up the access proxy to be incorporated with ansible container. 
- [x] create container 
- [ ] split container

**Comment by andrewkrug** [comment]
@gdestuynder I am capturing this here in an issue because I know we need to take the role alm built and move it to a container.

**Comment by gdestuynder** [comment]
container exists at https://github.com/mozilla-iam/federated_access_proxy/
still need to split it cleanly
