### ISSUE TITLE
flask oidc with session support

### ISSUE THREAD

**Issue by gdestuynder** [mozilla-iam/iam-project-backlog#139]
More RP's require a flask library for OIDC support.
Currently the libraries are not great
the goal of this issue is to implement session support to a flash library for everyone to use, the current selected library is ~~~https://github.com/puiterwijk/flask-oidc~~~ https://github.com/zamzterz/flask-pyoidc

cc @andrewkrug

**Comment by purelogiq** [comment]
https://github.com/zamzterz/flask-pyoidc actually looks like a very nice library as well and it seems to have more traction.

**Comment by gdestuynder** [comment]
https://github.com/puiterwijk/flask-oidc seems "cleaner" but I'd use whichever works for you :)

**Comment by gdestuynder** [comment]
Due to demand within infosec, support added in https://github.com/gdestuynder/Flask-pyoidc - however, while function, i noticed this also needs to pass over the id token exp. so this is not finished

see also https://github.com/mozilla-iam/Flask-pyoidc/pull/1
=> also added to sprint 8 target

**Comment by gdestuynder** [comment]
also done this ahead of time
currently set for review

**Comment by gdestuynder** [comment]
PR'd upstream https://github.com/zamzterz/Flask-pyoidc/pull/17

**Comment by gdestuynder** [comment]
remaining stuff to fix/nits via @andrewkrug (or we just wait for purelogiq to do it)
