### ISSUE TITLE
Consolidate IAM Mailing Lists and Communication Channels

### ISSUE THREAD

**Issue by hmitsch** [mozilla-iam/iam-project-backlog#149]
(Moving conversation from #141 to this separate issue)

Question: What is the "IAM Public Mailinglist" at this point?
Bonus question: Which IAM mailing lists / communication channels do we have?

@hmitsch listed:
> - **iam-dev@mozilla.com:** Some kind of internal (?) mailing list? By the way, I think we wanted to transition this one to Discourse. Could be an opportunity to merge it with the item mentioned below.
> - **iam@mozilla-community.org:** Discourse powered, public list.
> - **iam+internal@mozilla-community.org:** Discourse powered list, restricted to people on https://mozillians.org/group/iam-project/
> - **[mozilla.dev.identity](https://groups.google.com/d/msg/mozilla.dev.identity/)** (Note: I am admin)

@gdestuynder replied:
> it looks like we could merge many of these
> iam-dev @mozilla.com can redirect to iam+internal@mozilla-community.org
> mozilla.dev.identity could go to iam@mozilla-community.org or does it have to stay separated?

**Comment by hmitsch** [comment]
Remember, in early March we also discussed to re-purpose the IAM-DEV Mailing List: https://docs.google.com/a/mozilla.com/forms/d/1rxQTLPn04Qce_xKACFDCcEtGwnBGtXFMJejxL0n3rdc/edit

The result was:
<img width="682" alt="image" src="https://cloud.githubusercontent.com/assets/869692/26219957/26917b8c-3c11-11e7-93af-e84d3b587730.png">

**Conclusion:** Moving IAM-DEV to Discourse is a viable option.

**Comment by hmitsch** [comment]
Here is my suggestion:

**iam-dev@mozilla.com & mozilla.dev.identity should be merged with iam@mozilla-community.org.**

Consequences and implications:
- This would make the IAM-DEV list a Discourse powered, **public** list.
- This would be the go-to place for RP owners to find help with RP-specific IAM implementation questions.
- It would also be the place where public announcements from the [IAM Team](https://mozillians.org/group/iam-project/) go.
- Additionally it means that the IAM Discourse category becomes to place for public, Mozilla-related Identity conversations.

Open question:
- @gdestuynder @gene1wood do we expect non-public conversations to take place on the IAM-DEV mailing list? If yes, this proposal is invalidated.

Remark:
- iam+internal@mozilla-community.org is kept for IAM Team internal, non-public discussions. It is a Discourse powered list, restricted to people on https://mozillians.org/group/iam-project/.

**Comment by MichaelKohler** [comment]
While I'm not involved in that project, I think that having one internal channel is enough. I think it should either be iam+internal on Discourse or the iam-dev list on the mailing list platform. I don't think it should be both, just to make it more clear in terms of communication channels. Both would be internal and basically would serve the same purpose. 

I think Henrik's proposal makes sense in either way. If you need a private channel, let's use the iam+internal on Discourse if necessary.

**Comment by gdestuynder** [comment]
https://github.com/mozilla/iam-project-backlog/issues/149#issuecomment-302520062 <= r+

end scenario summary:
* iam@mozilla-community.org. (public, default)
* iam+internal@mozilla-community.org  (not public)

**Comment by gdestuynder** [comment]
@hmitsch this is blocking https://github.com/mozilla/iam-project-backlog/issues/141 which auth0 is pinging me about (they want to know if this works for us in production as it was a feature request)
Whom should this be assigned to?

**Comment by hmitsch** [comment]
Starting communication about iam@mozilla-community.org for public, RP-related IAM discussions.

**Comment by hmitsch** [comment]
* Informed iam-dev mailing list: https://groups.google.com/a/mozilla.com/d/msg/iam-dev/NnAO5cDlLvc/C08VON8LAQAJ

**Comment by gdestuynder** [comment]
Should we auto subscribe any new RP? (cc @jdow )
Can I use iam@mozilla-community.org for https://github.com/mozilla/iam-project-backlog/issues/141? (@hmitsch)

**Comment by hmitsch** [comment]
@gdestuynder yes and yes. 

* How would "auto-subscribe" work? Do we need @LeoMcA's input here?
* Totally in for sending info on #141 to that list!

PS: @LeoMcA how far ahead are with with the "display category subscribers" patch?

**Comment by gdestuynder** [comment]
auto-subscribe: we get RP's contact in ServiceNow when they request the integration

**Comment by LeoMcA** [comment]
> How would "auto-subscribe" work? Do we need @LeoMcA's input here?

That's not currently something supported in Discourse - users have to create their own accounts. Discourse does have the concept of invites, but that doesn't currently work with our accounts setup. Fixing that is being tracked here: https://github.com/mozilla/discourse/issues/24

> PS: @LeoMcA how far ahead are with with the "display category subscribers" patch?

Still in discussion: https://github.com/mozilla/discourse/issues/56
My thought was we only wanted to display the number - do we also want to expose the individual users to admins?

**Comment by hmitsch** [comment]
* Informed dev-identity mailing list: https://groups.google.com/forum/#!topic/mozilla.dev.identity/7VhizOJXxWc

**Comment by gdestuynder** [comment]
@hmitsch this is done / can close right?
