### ISSUE TITLE
Create, test and use a CNAME for RPs/Client that talk to auth0

### ISSUE THREAD

**Issue by gdestuynder** [mozilla-iam/iam-project-backlog#156]
Ex:
https://auth.sso.mozilla.com (PROD) CNAME auth.mozilla.auth0.com
https://auth.sso.allizom.org (DEV) CNAME auth-dev.mozilla.auth0.com

Then test that an RP works correctly with these. This makes it easier for us to change technology, add a proxy layer, etc in case it's needed without having to require RP's to change their setup.

**Comment by andrewkrug** [comment]
@gdestuynder what about SSL certificates?  Are you assuming we'll either add SAN to auth0 side or implement a lambda based proxy out the gate?

**Comment by andrewkrug** [comment]
Auth0 support ticket opened for adding subject alternative names https://support.auth0.com/tickets/24224

**Comment by gdestuynder** [comment]
yeah, either way. The goal of this issue is to verify feasibility as well. r+ on the ticket, if they can just use our SAN cert for example (that we would therefore provide them) then its easier

**Comment by gdestuynder** [comment]
wontfix'ed
