### ISSUE TITLE
Delivery team review of IAM Solution Architecture

### ISSUE THREAD

**Issue by hmitsch** [mozilla-iam/iam-project-backlog#16]
Draft solution architecture document:
* Lucidchart: https://www.lucidchart.com/documents/edit/4612e12b-e88b-4e17-a182-0278989c0582
* Author: MvK

Acceptance criteria:
* Delivery team (IT and ParSys) feels comfortable with the document
* Review meeting with MvK to discuss points which require clarification

**Comment by hmitsch** [comment]
Sent a proposal for the review process to the team.

**Comment by hmitsch** [comment]
Sent a mail listing artifacts to the team.

**Comment by tristanweir** [comment]
Team reviewed and provided comments back to mvk on 3/1/2017
