### ISSUE TITLE
Support Ajax-y sites (ie XHR support) with session refresh

### ISSUE THREAD

**Issue by gdestuynder** [mozilla-iam/iam-project-backlog#160]
See also: https://github.com/mozilla/mozilla-django-oidc/issues/133#issuecomment-308417531
- [x] Write patch
- [x] Open bug for phonebook
- [ ] Write github doc on this

**Comment by gdestuynder** [comment]
I wrote a hack for this:
https://github.com/mozilla/mozilla-django-oidc/issues/133#issuecomment-309113487

**Comment by gdestuynder** [comment]
reminder that once the doc is written for this a bug should be opened for phonebook
cc @floatingatoll @fox2mike

**Comment by gdestuynder** [comment]
issue was opened https://bugzilla.mozilla.org/show_bug.cgi?id=1401767

**Comment by floatingatoll** [comment]
@andrewkrug, send me a 60 minute meeting invite in January and we'll knowledge-transfer the work necessary to get this solved.
