### ISSUE TITLE
Automate client testing in auth0-deploy CI, include SAML clients

### ISSUE THREAD

**Issue by gdestuynder** [mozilla-iam/iam-project-backlog#162]
This is to avoid issues such as https://bugzilla.mozilla.org/show_bug.cgi?id=1375314

This must be done before any further merge to branches on auth0-deploy

- [x] Create tests
- [ ] Hook them up to CI

**Comment by gdestuynder** [comment]
See also  https://github.com/viorelaioia/auth0-tests

**Comment by hmitsch** [comment]
@viorelaioia had been creating lots of tests in the past weeks.
Now we need to hook this up into our CI pipeline. We know how to do it. It just needs to be done.
