### ISSUE TITLE
Bring Biztera to OIDC Conformant mode

### ISSUE THREAD

**Issue by gdestuynder** [mozilla-iam/iam-project-backlog#170]
Currently, its whitelisted - biztera fails to recognize dots in the assertion and prevents login

**Comment by mvk-mozilla** [comment]
Can I get the details about what specifically Biztera needs to do to come into compliance? Is there a document I can share with their developer?
Thanks!

**Comment by gdestuynder** [comment]
@mvk-mozilla they refuse any OIDC claim with dots in them such as:
https://sso.mozilla.com/groups = ['...']

This namespacing is required by auth0 and will soonish be enforced: https://auth0.com/docs/api-auth/tutorials/adoption/scope-custom-claims - when it is we won't be able to upgrade unless biztera handles claims with dots in them, basically.

There's no reason they wouldn't allow dots from an OIDC point of view

**Comment by lucioperca** [comment]
This is Zander from Biztera confirming receipt of this issue.

**Comment by lucioperca** [comment]
@gdestuynder @jdow @mvk-mozilla The issue should be resolved on our current build.

**Comment by gdestuynder** [comment]
@lucioperca awesome news and quick turn-around.
I verified and this is functional
thank you!
