### ISSUE TITLE
**Move this board to the IAM org** (see mail from gene)

### ISSUE THREAD

**Issue by gdestuynder** [mozilla-iam/iam-project-backlog#172]

**Comment by gdestuynder** [comment]
Moved the repo to mozilla-iam https://github.com/mozilla-iam/iam-project-backlog
Github updated the board links and redirected the old link (seems to be zero compat issues)

**Comment by hmitsch** [comment]
Looks great!

**Comment by gdestuynder** [comment]
found one issue: cannot create/convert/assign issues from the board at https://github.com/orgs/mozilla/projects/3 to https://github.com/mozilla-iam/iam-project-backlog (old issues do work though!)

**Comment by gdestuynder** [comment]
I had a quick chat with @tyearns - since we're not actually using the kanban functionality right now I've not recreated the board.
We using an issue with a list of issues instead (this one: https://github.com/mozilla-iam/iam-project-backlog/issues/163)
