### ISSUE TITLE
Create a CIS API `profile` endpoint

### ISSUE THREAD

**Issue by gdestuynder** [mozilla-iam/iam-project-backlog#174]
Start by creating the `profile` endpoint as read-only service/API.
Note that this is a stand-alone, OIDC compliant end-point that is orphaned as it does not have an associated `authorization` endpoint. It is to be used as a regular OAuth endpoint, basically, and cannot be discovered by OIDC discovery at the moment.
The goal of this API is to replace direct auth0 management API calls for RPs, and provide a consistent user profile

## Step 1
- [x] List use cases
- [x] Define JSON reply structure
- [x] Define how the API interaction will look like

## Step 2
- [ ] Create the serverless or EC2 project (add this to the doc as well)
- [ ] Add roles to be able to read data from dynamo db where the user profile resides
- [ ] Add scopes support in the access provider, as documented
- [ ] Add access token validation support to the project
- [ ] Add API replies for the `userinfo` endpoint
- [ ] Document how the access provider owners setup scope permissions in https://mana.mozilla.org/wiki/display/SECURITY/Auth0+Setup

## Optional?
- [ ] Add data classification to profile schema

### 1
I want to be able to query full profile information so that my RP has up to date user information, without having the user logging in. I need to be able to perform **search** queries

### 2
I want to query an API that gives me similar information to what the auth0 management endpoint gives me, but with only the contents of `user.app_metadata` as the rest of the contents are not directly relevant to the user profile

### 3
I want to be able to query, from the API: director name, manager name, developer name, developer bugmail for all user profiles, where directory name is one from a list of directors.
The resulting data is used to run bugzilla queries on needinfos and review requests.

### 4
I want to create an org chart from querying the API, similar to phonebook's org chart

### Older notes

> Possiblities:
> - SCIM interface
> - Own API to the vault
> - etc
> 
> Example of integration with Auth0: 
> https://github.com/mozilla-services/tecken/pull/245/commits/eb14f25c8d46a0ca38068b09d3130e2a80719c5d
> 
> Pros of having our own implementation:
> - ability to verify which data/users are verified by the API/logs
> - ability to check if session refresh is truly supported by the RP
> - ability to grant access by default w/ limited privileges (if RP knows of the user already it gets read access to that user status by default for example)

**Comment by gdestuynder** [comment]
cc @eliperelman

**Comment by andrewkrug** [comment]
- [ ] Create serverless functions project
- [ ] Add roles to be able to read data from dynamo db
- [ ] Add scoped oAuth endpoint support 
- [ ] Add custom authorizer to serverless function project
- [ ] Test bearer token blacklisting
- [ ] Decide on whether SCIM is the right fit.
