### ISSUE TITLE
Account Linking

### ISSUE THREAD

**Issue by hmitsch** [mozilla-iam/iam-project-backlog#2]
Auth0 will link the various accounts of a person to a single identity.

**Comment by hmitsch** [comment]
Blocked by LDAP profile definition

**Comment by gdestuynder** [comment]
see also https://github.com/mozilla/iam-project-backlog/issues/35

**Comment by gdestuynder** [comment]
see also https://github.com/mozilla/iam-project-backlog/issues/4

**Comment by hmitsch** [comment]
see also https://github.com/auth0/rules/issues/71

**Comment by gdestuynder** [comment]
@hmitsch why is this reopened?
