### ISSUE TITLE
Set the cis_tests in InfoSec infrastructure

### ISSUE THREAD

**Issue by viorelaioia-zz** [mozilla-iam/iam-project-backlog#202]

**Comment by flamingspaz** [comment]
Related: https://github.com/mozilla/parsys/issues/236

**Comment by andrewkrug** [comment]
@viorelaioia I slacked you on this but it looks like to achieve this we are going to need a docker container to run these tests from within the infosec account.

**Comment by bulletproofsysadmin** [comment]
An alternative, for now, might also be for this be webhook based and post the status to slack?
