### ISSUE TITLE
Create a loopback driver to populate the CIS groups table.

### ISSUE THREAD

**Issue by andrewkrug** [mozilla-iam/iam-project-backlog#215]
In order to facilitate the creation of GSuite GDrives and Slack access as a user when I join a group the event needs to also populate the groups table that exists in the identity vault.  

- [ ] Add code to cis_functions to build out group memberships table for quick search.

**Comment by gdestuynder** [comment]
since we're doing this without having the feature im super iceboxing this for now ;-)
