### ISSUE TITLE
ID Token too Large

### ISSUE THREAD

**Issue by andrewkrug** [mozilla-iam/iam-project-backlog#218]
While doing testing for AWS Federated access we discovered that if a user has too many groups our ID token is too large. 

- [ ] Create an auth zero rule to truncate the token as needed.
- [ ] Indicate in a claim that more group data is available in the CIS user API.

Blocked by #174

**Comment by gdestuynder** [comment]
we've reduced the token through oidc claims
while its still possible to overflow through group data, its very unlikely at this time and thus im considering this fixed
