### ISSUE TITLE
Decide on whether to have immutable IDs for all users

### ISSUE THREAD

**Issue by andrewkrug** [mozilla-iam/iam-project-backlog#220]
This is a complex conversation.  The future of identity at Mozilla could take many paths we should discuss having a "non auth0 deterministic identifier" instead of relying so heavily on the auth0 ID.

- [ ] Reach a decision on whether to have the conversation at all
- [ ] Decide 
- [ ] Report

**Comment by andrewkrug** [comment]
- [ ] Reach a decision on whether to have the conversation at all
- [ ] Decide 
- [ ] Report

**Comment by gdestuynder** [comment]
we have an immutable id: `user_id`
we have also decided on attempting to make `primaryEmail` mutable-yet-unique
