### ISSUE TITLE
Productionalize integration of HRIS Data connector

### ISSUE THREAD

**Issue by andrewkrug** [mozilla-iam/iam-project-backlog#221]
- [ ] create s3_bucket and role 
- [ ] create IAM AWS service account
- [ ] deliver credentials to jdow
- [ ] @jdow to create process to copy workday extract to s3 bucket
- [ ] create cloudwatch event cron
- [ ] test
- [ ] go live with new hris claims
- [ ] switch RPs using HRIS claims to use new connector

**Comment by gdestuynder** [comment]
i believe its done
