### ISSUE TITLE
attempt work-around to integrate LDAP groups in Auth0 instead of CIS until LDAP publisher is live

### ISSUE THREAD

**Issue by gdestuynder** [mozilla-iam/iam-project-backlog#223]
- [x] write rule in auth0
- [x] test deploy
- [x] Deploy in prod

**Comment by gdestuynder** [comment]
dupe of https://github.com/mozilla-iam/iam-project-backlog/issues/174 will use #174

**Comment by gdestuynder** [comment]
this is done in #152 needs test/review and prod deploy if successfull

**Comment by andrewkrug** [comment]
@flamingspaz let me know when we can test this with Mozillians.org current staging.

**Comment by andrewkrug** [comment]
Approve this https://github.com/mozilla-iam/auth0-deploy/pull/152 after testing.

**Comment by viorelaioia-zz** [comment]
Hey @gdestuynder, @andrewkrug , do you need help with testing? If so, can I get more info on how to test this? Thanks!

**Comment by gdestuynder** [comment]
@viorelaioia yes! :)
this is on auth-dev (so mozillians staging, and https://social-ldap-pwless.testrp.security.allizom.org/ for example)

If you have a passwordless email such as gdestuynder@mozilla.com *and* a LDAP email which is also gdestuynder@mozilla.com, logging in with passwordless will fail with an error telling you to use LDAP, and LDAP will work.

In other word, for the same email address used for login, if you have accounts with passwordless,google,github,LDAP (any mix of these, or even all of them), you will get an error unless you use the "highest" "most trusted" identification method.
The order of trust is: passwordless < google < github < LDAP

Does that make sense?

**Comment by viorelaioia-zz** [comment]
@gdestuynder , I created a document where I added all the cases I tested: https://docs.google.com/document/d/1AuGNgNehsuhtmnRb1LeUPA7WcLhjZ8KZHqftUM0ZJKw/edit
Can you take a look and let me know if all the results I got are the ones expected? Also, I added a few questions, as I was not sure if the specific behavior is intended. I hope I covered all cases.

**Comment by andrewkrug** [comment]
@gdestuynder I've approved this PR as of today.  Can we get it to prod auth0?

**Comment by gdestuynder** [comment]
CAB https://mozilla.service-now.com/nav_to.do?uri=change_request.do?sys_id=20eb63f213ad83c0472ed2f18144b093

**Comment by gdestuynder** [comment]
@viorelaioia continuing discussion on https://github.com/mozilla-iam/auth0-deploy/pull/154

**Comment by gdestuynder** [comment]
in prod
