### ISSUE TITLE
Homepage returned instead of user's profile, after login

### ISSUE THREAD

**Issue by viorelaioia-zz** [mozilla-iam/iam-project-backlog#229]
STR:
1. When being logout, go to a user's profile page E.g: https://mozillians.org/en-US/u/freddyb/
2. Click Login button
3. Select "Login with Ldap", enter credentials and click Log in button  

Expected results:
User is redirected to the profile page from step 1

Actual results:
User is redirected to homepage

**Comment by gdestuynder** [comment]
I suspect this might be 'a feature' :D anyhow, OIDC will always redirect to the `redirect_uri` as per spec, and the calling RP (in this case mozillians) can choose to redirect back elsewhere (including by passing an additional parameter to the OIDC request IIRC)
Right now their next redirect is `/` (which is common amongst RPs)

**Comment by gdestuynder** [comment]
im guessing this is fixed
