### ISSUE TITLE
Alert UI Color Updates

### ISSUE THREAD

**Issue by mbransn** [mozilla-iam/iam-project-backlog#231]
Based on the latest color updates to the [Mozilla Brand Guidelines](https://mozilla.ninja/visualelements/), I will apply new colors to the alert banner and notification center UI.

**Comment by mbransn** [comment]
Based on updated Mozilla [brand colors](https://mozilla.ninja/visualelements/), new UI color options (some at darker densities than guideline default value) have been applied and are being reviewed with the brand team.

cc @andrewkrug @comzeradd @hmitsch

**Success Banner `#14c887`**
<img width="1466" alt="01-sso-success-green-14c887" src="https://user-images.githubusercontent.com/18686986/31360557-d6ae208e-ad03-11e7-9184-9a69c57b0fed.png">

**Low Risk Banner `#000000`**
<img width="1455" alt="02-sso-low-risk-black-000000" src="https://user-images.githubusercontent.com/18686986/31360567-e2e8edca-ad03-11e7-9cee-e9ba7c5ea149.png">

**Medium Risk Banner `#009696`**
<img width="1465" alt="03-sso-medium-risk-blue-009696" src="https://user-images.githubusercontent.com/18686986/31360578-f1b45a60-ad03-11e7-9aa2-843110072c3c.png">

**High Risk Banner `#ffc300`**
<img width="1465" alt="04-sso-high-risk-yellow-ffc300" src="https://user-images.githubusercontent.com/18686986/31360590-01a8a372-ad04-11e7-8825-bcf5531cd026.png">

**Maximum Risk Banner `#ff4f5e`**
<img width="1465" alt="05-sso-maximum-risk-red-ff4f5e" src="https://user-images.githubusercontent.com/18686986/31360602-0d5c55d8-ad04-11e7-97c5-a0eee8b4c2b9.png">


**Notification Center w/above colors applied**
![06-sso-notification-center](https://user-images.githubusercontent.com/18686986/31360609-164112ce-ad04-11e7-9935-61468bcc76e4.jpg)

[Sketch File](https://drive.google.com/open?id=0B0vmiicLLrGuTUlUMG10d0xsaHM) for implementation and version reference.

**Comment by comzeradd** [comment]
@m-branson looks nice! Can you provide the color codes for the alert buttons too? I see these use a lighter background color variation.

**Comment by mbransn** [comment]
@comzeradd thanks! The alert buttons are all the same: background-color: #FFFFFF @ 0.2 opacity.

**Comment by gdestuynder** [comment]
ive set that to backlog and would ask if we apply these things in sprint 18 (next sprint), but feel free to change to in progress if thats actually all being done right now

**Comment by comzeradd** [comment]
This is already in progress. At least the color updates. I'll open a new issue to track the work for the Notifications Center, that most likely fit into the next sprint.

**Comment by gdestuynder** [comment]
@m-branson wouldn't the secondary color for blue be close to the standard level colors? (HEX: #00458b)

**Comment by mbransn** [comment]
@gdestuynder yes, it's quite close. Realistically though, I'd prefer to keep these colors in the primary family. If you have a strong argument for the other, happy to consider it. :)

**Comment by gdestuynder** [comment]
The main argument is consistency with the standard levels (https://wiki.mozilla.org/Security/Standard_Levels) and that the current "blue" looks "green" to many
In other words "kinda strong" ;-)
I understand that the harmony of the tones of the palette may be an issue with the blue, and in a pragmatic world i'd just say "tweak the greenish blue to look more blue while keeping a similar tone".

We use the standard level colors in RRAs, risk register, heatmap, and other places - and this is sufficiently far from the standard in this case that it no longer look similar.

**Comment by mbransn** [comment]
Thanks @gdestuynder ... good clarity. Will the standards levels change to align with the brand update? As is, they appear dated. If not updating, we should maintain the current standard and forgo the 'brand focused colors' for all of these instances. It does not make sense to change alert colors in only one instance.

To summarize:
- From an ideal design stand point: the Mozilla Security Standard Levels adjust to align with the new brand colors.* (We continue to fine tune the blue, perhaps using the secondary blue.)
- If this is not possible, forgo using new colors and continue to use current Standard Levels for continuity.

*If this happens we will wait to implement until brand colors are truly 'finalized'.

**Comment by mbransn** [comment]
@comzeradd note the new color usage for Medium alert level.

cc @gdestuynder 

**Medium Risk Banner** `#00458b`

![screen shot 2017-10-11 at 4 33 08 pm](https://user-images.githubusercontent.com/18686986/31472449-b8bdec66-aea3-11e7-936e-494e8ed95c41.png)

**Notification Center w/Updated Medium Risk `#00458b`**

![notification-center](https://user-images.githubusercontent.com/18686986/31472470-cad9ebc0-aea3-11e7-96e7-53b9aa1d7928.png)

**Comment by gdestuynder** [comment]
this is done
