### ISSUE TITLE
IC & managers list

### ISSUE THREAD

**Issue by sylvestre** [mozilla-iam/iam-project-backlog#238]
With the [release mgmt auto nag tool](https://github.com/mozilla/relman-auto-nag/), we are sending reminders to developers.

We would need to have the list of employees, their titles and their managers to do that.

Thanks.

**Comment by andrewkrug** [comment]
We will be able to give you this data from our person-api in about 2-weeks.  https://github.com/mozilla-iam/person-api

HRIS claims are actively being worked on in the current sprint.

**Comment by sylvestre** [comment]
Great, thanks!

**Comment by andrewkrug** [comment]
I'll update you when we have something in staging you can start developing against.

**Comment by emceeaich** [comment]
https://github.com/eliperelman/bz-dev-stats-server will need this API as well. @eliperelman

**Comment by sylvestre** [comment]
@andrewkrug do you have an update on this? Thanks
