### ISSUE TITLE
Wireframe Log In/Sign Up Flow (Mozillians.org)

### ISSUE THREAD

**Issue by mbransn** [mozilla-iam/iam-project-backlog#24]
Based in Mozillians.org, I will wireframe Log In/Sign Up experience for users. Both desktop and mobile to be represented.

**Log In Paramenters:**
- Based in the Auth0 Lock
- Allows for password and passwordless entry
- Two factor authentication is present for unregistered devices (will this always be Duo?)
- Provides option to remember user
- User can easily move back to the beginning of flow to sign up with different email

**Sign Up Parameters:**
- For initial iterations, Sign Up is decentralized from the Auth0 Lock (lives at the RP level). Eventual goal being one, centralized single sign up and log in experience.
- New (unrecognized) user emails are automatically routed through Sign Up flow
- Sign Up form implementation for initial user account set up
- Successful Sign Up will route the user to a dashboard, on Mozillians.org this is a new feature.

**Comment by mbransn** [comment]
V2 clickable prototypes are available at the links below. Comments can be viewed and added via "comment mode", see the desktop prototype for universal annotations.

**Note:** V1 consisted of two options which were user tested, results outlined [here](https://docs.google.com/document/d/1TjUprptHMKTrrBubno4Qu6Gm6UC9vfUy_ZOpcFE1tUU/edit?usp=sharing).

**Desktop Prototype:** http://bit.ly/2kF7XtO
Contains annotation in 'comments' mode.

**Mobile Prototype:** http://bit.ly/2lL8o5X
Possible to view on desktop as well as on mobile device.

**Sketch Cloud:** https://sketch.cloud/s/my87
Note that these flat comps are out of order, utilize prototypes above to view user flow. Sketch file attached below.

[MOZ_IAM_Auth0.sketch.zip](https://github.com/mozilla/iam-project-backlog/files/814904/MOZ_IAM_Auth0.sketch.zip)

**Comment by a-kilroy** [comment]
@m-branson Lets determine some testing for this. I'll send you an email and we can update this issue when we have a test decided.

**Comment by mbransn** [comment]
@a-kilroy Sounds good. I've updated my initial comment to include a link to initial user testing results as well.

**Comment by mbransn** [comment]
**A qualitative IAM user test outline has been created to include three flows:**

1. User Signs Up
2. User Logs In using a password
3. User Logs In without a password (passwordless)

Next step is test implementation utilizing usertesting.com, which will be tracked via issue #46

**Comment by mbransn** [comment]
Cleaned up Sketch file and updated mobile versions to mirror the desktop edits made for testing.

**Desktop Prototype:** http://bit.ly/2kF7XtO

**Mobile Prototype:** http://bit.ly/2lL8o5X

**Sketch Cloud:** https://sketch.cloud/s/my87

[MOZ_IAM_Auth0.sketch.zip](https://github.com/mozilla/iam-project-backlog/files/843031/MOZ_IAM_Auth0.sketch.zip)
