### ISSUE TITLE
(Auth0 Lock) Wireframe Alt-RP Version of Log In/Sign Up (Discourse)

### ISSUE THREAD

**Issue by mbransn** [mozilla-iam/iam-project-backlog#25]
To help visualize the updated Log In/Sign Up flow, I will wireframe an alternate RP version using Discourse as the model. 

This version will utilize the same functionality as our Mozillians.org wireframes and help to outline which screens are central to the Auth0 Lock vs. decentralized at the RP level.

In addition we will use this as an opportunity to begin highlighting and cataloging use case differences at the RP level for Sign Up.

**Comment by mbransn** [comment]
Desktop AIM wireframe prototype for Discourse (as an alternate RP to Mozillians.org): 
http://bit.ly/2lLw5OI

@LeoMcA @johngian @akatsoulas @comzeradd please make an initial review and log any questions/requests here or within the prototype's comments.

Questions to keep in mind:
- Does this capture sufficient user information at user sign up for Discourse vs. Mozillians.org?
- Is this log in flow and its options equally efficient for Discourse and Mozillians.org?
- Anything missing that is unique to Discourse and needs to be accounted for?
- Anything that is superfluous and only beneficial to Mozillians.org, but not to Discourse (or potentially another RP)?

Mobile version will be built once an initial review of this desktop version is completed.

Sketch file:
[MOZ_IAM_Auth0.sketch.zip](https://github.com/mozilla/iam-project-backlog/files/798380/MOZ_IAM_Auth0.sketch.zip)

**Comment by mbransn** [comment]
Both desktop and mobile versions of the Alt-RP (Discourse) wireframe flow are available via the links below:

**Desktop:**
http://bit.ly/2lLw5OI

**Mobile:**
http://bit.ly/2mMilk3

@LeoMcA -- not sure if you've had a chance to run through this, but please let me know if you have any Discourse specific concerns prior to end of this sprint.

**Sketch file:**
[MOZ_IAM_Auth0.sketch.zip](https://github.com/mozilla/iam-project-backlog/files/814902/MOZ_IAM_Auth0.sketch.zip)

**Comment by LeoMcA** [comment]
Looks good to me!

**Comment by mbransn** [comment]
**A qualitative IAM user test outline has been created to include three flows:**

1. User Signs Up
2. User Logs In using a password
3. User Logs In without a password (passwordless)

This test utilizes the Mozillians.org wireframe version ( #24 ), which consists of the same proposed Log In/Sign Up flows. Next step is test implementation utilizing usertesting.com, which will be tracked via issue #46

**Comment by mbransn** [comment]
Cleaned up Sketch file and updated mobile to mirror desktop edits made for testing.

**Desktop:** http://bit.ly/2lLw5OI

**Mobile:** http://bit.ly/2mMilk3

**Sketch Cloud:** https://sketch.cloud/s/my87

[MOZ_IAM_Auth0.sketch.zip](https://github.com/mozilla/iam-project-backlog/files/843041/MOZ_IAM_Auth0.sketch.zip)
