### ISSUE TITLE
Mozillians.org User Dashboard Wireframe

### ISSUE THREAD

**Issue by mbransn** [mozilla-iam/iam-project-backlog#27]
I will wireframe a new user dashboard for Mozillians.org, versions will include desktop and mobile.

These wireframes will reflect changes made to the Mozillians sign up experience and recommend updates based on user experience and user interface for Mozillians as a whole.

When initial versions are ready they will be added to the Mozillians prototype and be user tested.

**Comment by gdestuynder** [comment]
@hmitsch is this still valid, or is this something you track in the mozillians.org org/repo instead?

**Comment by hmitsch** [comment]
Let's close it.
