### ISSUE TITLE
(L) Auth0 enriched profiles (formerly acct linking)

### ISSUE THREAD

**Issue by hmitsch** [mozilla-iam/iam-project-backlog#3]
Acceptance Criteria:
* Work on https://github.com/mozilla-iam/auth0-deploy/pull/86#issuecomment-277792988: resolve blocker

**Comment by tyearns** [comment]
Closing per Kang's recommendation.

**Comment by gdestuynder** [comment]
@tyearns is this closed or open ? ;-)

**Comment by tyearns** [comment]
I'm awaiting confirmation. Was under the impression that you were awaiting final approval from the team. Can I close it?

**Comment by gdestuynder** [comment]
yep thanks - https://github.com/mozilla/iam-project-backlog/issues/57 is the same thing and a better place/more info
