### ISSUE TITLE
Need: script that set disable LDAP users as blocked in auth0

### ISSUE THREAD

**Issue by hmitsch** [mozilla-iam/iam-project-backlog#30]
@gdestuynder commented on [Fri Nov 04 2016](https://github.com/mozilla-iam/mozilla-iam/issues/1)

https://auth0.com/docs/api/management/v2#!/Users/patch_users_by_id
Update block to "true"

---

@gdestuynder commented on [Tue Nov 08 2016](https://github.com/mozilla-iam/mozilla-iam/issues/1#issuecomment-259214140)

Should also list all email aliases and block any other account that uses that email as their primary identifier (for ex if the email is used by a github account as main identifier)

---

@gdestuynder commented on [Wed Feb 15 2017](https://github.com/mozilla-iam/mozilla-iam/issues/1#issuecomment-279882478)

@jdow isn't this implemented?

**Comment by gdestuynder** [comment]
@jdow is this implemented? (as in, isnt it here already?)

**Comment by jdow** [comment]
Yes, this was implemented a long time ago.
