### ISSUE TITLE
Change auth0 auth-dev github extension to pull from development branch

### ISSUE THREAD

**Issue by hmitsch** [mozilla-iam/iam-project-backlog#32]
@gene1wood commented on [Fri Nov 11 2016](https://github.com/mozilla-iam/mozilla-iam/issues/9)

Currently it pulls from master. Change it to development. It might require disabling and re-enabling the extension as there's no apparent way to change the branch.

---

@gdestuynder commented on [Tue Nov 15 2016](https://github.com/mozilla-iam/mozilla-iam/issues/9#issuecomment-260745103)

Currently we cannot change settings or delete the extension
Depends on https://support.auth0.com/tickets/16844

---

@gdestuynder commented on [Wed Feb 15 2017](https://github.com/mozilla-iam/mozilla-iam/issues/9#issuecomment-279882337)

note, we can now change settings.
I would actually vote to keep master and wontfix this though, since we've been using it for a while and it's rather standard.

**Comment by gdestuynder** [comment]
As per previous comment I vote to close this

cc @gene1wood

**Comment by gene1wood** [comment]
Sure thing. Committing to master will continue to auto deploy to auth0-dev
