### ISSUE TITLE
Process and store email delivery records

### ISSUE THREAD

**Issue by hmitsch** [mozilla-iam/iam-project-backlog#34]
@gene1wood commented on [Mon Jan 23 2017](https://github.com/mozilla-iam/mozilla-iam/issues/12)

Currently AWS SES notifications regarding email delivery are sent to an AWS SNS Topic which is in turn subscribed to by a Google Group.

Searching in Google Groups for a specific user's delivery attempt isn't possible because the message content is JSON and Google Groups is expecting plan text.

I'd recommend we write a AWS Lambda function to take these SNS notifications, parse the JSON and insert each record into a DB (e.g. AWS Dynamo) so that we can search them.

---

@gene1wood commented on [Tue Jan 24 2017](https://github.com/mozilla-iam/mozilla-iam/issues/12#issuecomment-274648873)

Or emit the events to MozDef instead of storing them in a DB.

**Comment by gdestuynder** [comment]
@gene1wood do you think we still need this?

**Comment by gene1wood** [comment]
We don't `need` it so long as we don't need to do any troubleshooting of email delivery to users. Happy to get others thoughts.

**Comment by gdestuynder** [comment]
@hmitsch ^^ (i think you're the 'others thoughts' here :)

**Comment by hmitsch** [comment]
@gene1wood and @gdestuynder, I'd suggest we close the issue. We have done well in the past and I would not invest in this type of "operational helper tool" at the moment.

Best regards,
   Henrik
