### ISSUE TITLE
Link user identities automatically by email

### ISSUE THREAD

**Issue by hmitsch** [mozilla-iam/iam-project-backlog#35]
@tristanweir commented on [Wed Feb 15 2017](https://github.com/mozilla-iam/mozilla-iam/issues/13)

_Replaces https://github.com/mozilla-iam/auth0-deploy/issues/15_

Example: https://github.com/auth0/rules/blob/master/rules/link-users-by-email.md

---

@gdestuynder commented on [Wed Feb 22 2017](https://github.com/mozilla-iam/mozilla-iam/issues/13#issuecomment-281754064)

https://github.com/mozilla-iam/auth0-deploy/pull/86
https://github.com/mozilla-iam/auth0-deploy/issues/15

**Comment by gdestuynder** [comment]
https://github.com/mozilla-iam/auth0-deploy/issues/15#issuecomment-281391602
https://github.com/mozilla-iam/auth0-deploy/pull/86#issuecomment-281390853

This was already closed, and still cannot be done properly. Instead, linking manually in the profile via Mozillians.org is the working solution, at least until https://github.com/auth0/rules/issues/71 is resolved

**Comment by gdestuynder** [comment]
we noticed today that this is an issue with discourse for example, as 2  accounts (eg passwordless  and ldap) can have the exact same primary email, which causes a conflict

**Comment by hmitsch** [comment]
Do we already have a solution for that? Would we want to change Discourse to prohibit two accounts with the same primary email?

**Comment by gdestuynder** [comment]
@LeoMcA is going to handle it on the discourse side for now and I believe make them appear as the same account there (correct me if im wrong)
not a great/generic solution but works for discourse purposes
