### ISSUE TITLE
Modify email template to provide magic link and number code

### ISSUE THREAD

**Issue by hmitsch** [mozilla-iam/iam-project-backlog#36]
@tristanweir commented on [Wed Feb 15 2017](https://github.com/mozilla-iam/mozilla-iam/issues/14)

_Replaces https://github.com/mozilla-iam/auth0-deploy/issues/22_

Also, change email send confirmation page to something that would accept the code and continue the auth flow.

**Comment by gdestuynder** [comment]
We might get this during the lock rewite, though its far from a priority so leaving in icebox for now

**Comment by gdestuynder** [comment]
iceboxing into the closed bucket ;-)
