### ISSUE TITLE
(M) Mozillians.org GitHub username integration

### ISSUE THREAD

**Issue by hmitsch** [mozilla-iam/iam-project-backlog#4]
**User Story:**
As a Mozillian I want to add my Github user name to my Mozillians.org profile in order to link it once Account Linking is set up in the Auth0 implementation.

**Acceptance Criteria:**
* Mozillians.org account panel has a field to enter a Github user name
* Ownership of this Github user name is verified via a call to Auth0
* Migration for existing Github user names
* Out of Scope: Do NOT add Github social login to Mozillians.org

**Comment by gdestuynder** [comment]
note that we now want GitHub as login method but we also STILL want this to verify GitHub as an external account in mozillians.org

**Comment by hmitsch** [comment]
Since quite a lot of time passed, here's an update.
This intent is part of **Solution 1** implementation from https://docs.google.com/document/d/1xu92qiRoECSjWP1TqCOVnzrNcWRH5Z7UsxoR3PDM8LQ/edit

**Comment by gdestuynder** [comment]
its done
