### ISSUE TITLE
Contractor Identity

### ISSUE THREAD

**Issue by jeffbryner** [mozilla-iam/iam-project-backlog#43]
Executives would like discreet identities for contractors vs employees to allow for: 
1) Proper representation in the public (i.e. bob@contractor.mozilla.com vs bob@mozilla.com)
2) Discreet email distribution lists for FTE vs Contractors to facilitate information dissemination.

**Comment by gdestuynder** [comment]
@jeffbryner  do you know if we get this data anywhere, like workday for example?
This would require provisioning their account and email differently at the workday =>CIS integration if we do this. I believe its doable.

**Comment by jeffbryner** [comment]
We do get contractor information from workday. I don't know how it's flagged, however.

**Comment by gdestuynder** [comment]
i think its an employee type attribute in ldap/workday, so we could use it.
I think we can start by having them in a special workday group (this is how we currently plan the CIS integration anyway) and after that if we still want to do this, point the domains correctly and create the users in a separated ldap ```ou```

cc @jdow for feedback on that too

**Comment by gdestuynder** [comment]
@andrewkrug do you know if we get this from the workday report?
