### ISSUE TITLE
(LDAP Integration) Technical design on CIS

### ISSUE THREAD

**Issue by hmitsch** [mozilla-iam/iam-project-backlog#51]
Acceptance Criteria:

* [x] diagram
* [x] data flow
* [x] user stories

**Comment by gdestuynder** [comment]
# Sequence diagram ("data flow")

![change integration service 1](https://cloud.githubusercontent.com/assets/956866/24316941/a1915740-10af-11e7-8b6d-8ff6b8c2973a.png)


```
title Change Integration Service

participant "Mozillians.org\nWorkDay\nEtc." as input
database "Change\nIntegration\nQueue" as cisq
participant "Change\nIntegration\nService" as cisw
database "User Profile Database" as profiledb
participant "LDAP" as ldap
participant "Auth0" as auth0

==Forward flow (**write** user profile updates)==
box over input: user-profile.json\n--user_id:...\nprimaryEmail:...--
input->cisq: Send full (no delta) user-profile update
cisw->cisq: pick-up next work item from queue
cisw->cisw: validate changes
cisw->cisw: integrate data in user profile
consider Database store method
cisw->profiledb: store raw requested change\n**(SQL, Git?**
cisw->profiledb: store new version of user profile\n**(SQL, Git?)**
end
cisw->cisq: Send failure message if any (failed validation or integration)
input->cisq: pick-up next failure message is any
cisw->ldap: store new version of user profile for LDAP\n**(LDAP Call)**
cisw->auth0: store new version of user profile in auth0 user.metadata\n**(Auth0 API Call)**

==Return in-flow (**get** user profile updates on login/session refresh)==
input->auth0: User login or session refresh (SAML, OIDC, WSFED)
auth0->auth0: process user.metadata into user profile\n**(Auth0 rule)**
auth0->input: New user info (id_token, SAML assertion)
box over input: user-profile.json/xml\n--user_id:...\nprimaryEmail:...--

==Return async-flow (**get** user profile update at RP's request)==
input->auth0: Asynchronous user update request to --https:\/\/auth-dev.mozilla.auth0.com/userinfo
auth0->auth0: process user.metadata into user profile\n**(Auth0 rule)**
auth0->input: New user info (JSON)
box over input: user-profile.json\n--user_id:...\nprimaryEmail:...--
```

**Comment by gdestuynder** [comment]
# High level diagram
https://mana.mozilla.org/wiki/display/SECURITY/IAM#IAM-Designarchitectureanddiagrams

**Comment by gdestuynder** [comment]
moved to "in progress" since ive done this as part of sprint3 as requested initially... so well, its mostly done ;-) Its' been apparently moved back according to https://github.com/mozilla/iam-project-backlog/issues/48 (but ive seen that after finishing this)

notification: @tyearns

**Comment by gdestuynder** [comment]
Review needed:

- [ ] @jdow 
- [x] @andrewkrug 
- [ ] @gene1wood 
- [ ] @flamingspaz 
- [ ] @akatsoulas 
- [ ] @johngian

**Comment by andrewkrug** [comment]
I have reviewed this diagram and discussed with Kang.  There is some consensus needed on who is building what and what is going to be in the MVP.  For example:

- Does MVP need to include versioning for user profile and changed objects... probably not.  
- What are the use cases we are writing for here?  Can we mock up some dummy users and scenarios to design / test against?  
- Should was take certain stories for the build of CIS in pairs?

**Comment by gdestuynder** [comment]
I updated the diagram and pushed all this to git for better change tracking and notifications as aforementioned:

https://github.com/mozilla-iam/ldap-postgres-reference/pull/3/files

@andrewkrug I agree we should write up a few user stories just to be sure we're not missing anything. Even a lightweight thing like an issue/text file with a bunch of bullet points would be better than nothing :)

Edit: and thus I did that: https://github.com/mozilla-iam/ldap-postgres-reference/pull/3/commits/0e4d57fd159a4cb75470eee15529eb2084cd1658 (user stories)

**Comment by gdestuynder** [comment]
This is the capture of the work/decision:

https://docs.google.com/document/d/1eoQ5K3bTCuUYaTGmLtFSdNq-hzXZCRM4Cjuhw1Vv6rI/edit#


<img width="396" alt="image" src="https://cloud.githubusercontent.com/assets/956866/25238469/5ff5a69e-25a2-11e7-9634-e5e07231ab5b.png">

**Comment by gdestuynder** [comment]
Work for CIS implementation is at https://github.com/mozilla-iam/cis
