### ISSUE TITLE
Define Auth0 Dashboard Release Strategy

### ISSUE THREAD

**Issue by tyearns** [mozilla-iam/iam-project-backlog#58]
- Define a communication plan announcing availability of the Auth0 dashboard 
     - Release Auth0 dashboard
     - Turn-off Okta dashboard 
- Determine strategy and requirements for continually transitioning applications from Okta to Auth0 
     - Create notification channel for each user community
          - Enable Dashboard alerts to appear whenever an app is cutover
     - SAML assertion requirements
     - OID assertion requirements
- Determine DR process and technical/operational requirements for reverting back to Okta SSO as needed (roles/responsibilities, workflows)

**Comment by tyearns** [comment]
@jdow  @andrewkrug should we put together overview of what's involved for each of the RP owners prior to initiating Group 1 cut-overs? I think I should craft some kind of announcement to assist with coordinating as needed.

**Comment by jdow** [comment]
This was done a long time ago.
