### ISSUE TITLE
RP Cutover - Verify and de-scope RP's targeted to be decommisioned

### ISSUE THREAD

**Issue by tyearns** [mozilla-iam/iam-project-backlog#61]
Identify applications that may be decommissioned in the near-future - Jabba
- Verify and remove applications to be decommissioned immediately from the Auth0 dashboard cut-over plan
- Coordinate cut-over timing and activities with system owners for RP's targeted to be decommissioned after their intended cut-over period

**Comment by tyearns** [comment]
**RP's Flagged for Decommissioning:**
- OpSec IP Query
- ClearBenefits
- Jobvite
- Sandbox AWS
- Yammer
- Admin - Admin AWS
- Admin - Production AWS
- Consolidated Billing AWS
- Production AWS
- Stage AWS
- Temp Admin - Consolidated Billing AWS
- Admin - Stage AWS
- FCm Travel Solutions Client Portal

**Comment by jdow** [comment]
This work is done.
