### ISSUE TITLE
Implement Phonebook/CIS integration

### ISSUE THREAD

**Issue by tyearns** [mozilla-iam/iam-project-backlog#63]
Implement Phonebook(PHP)/CIS integration (Should remain active for 12 or so months)
- Redesign requirements TBD 
- Proposed future-state may be to enable read-only state, routing updates to be executed via Mozillians.org

**Comment by floatingatoll** [comment]
(What's CIS?)

**Comment by tyearns** [comment]
Apologies, this story is part of the LDAP/Mozillians integration for the IAM project, was erroneously assigned to you.

**Comment by gdestuynder** [comment]
@floatingatoll will AFAIK be the person doing the work so this might be assigned to him, but this is not ready for him (it depends on https://github.com/mozilla/iam-project-backlog/issues/51 and implementation of CIS)

**Comment by gdestuynder** [comment]
I believe this is no longer planned (as we kept LDAP compatibility instead), closing
