### ISSUE TITLE
Student user Log In/Sign Up use case (Thimble)

### ISSUE THREAD

**Issue by mbransn** [mozilla-iam/iam-project-backlog#64]
**From Luke working on Thimble (MoFo):** 

> We currently have student users who don't have an email, but still need to sign up. Currently they use a fake email, how would this work with the new Log In/Sign Up flow when it integrates to Thimble? These student users are an important part of our community, need to provide a way from them to sign up for a profile without email.

@hmitsch this came out of the biweekly MoFo design review I've started attending. Is this something we've accounted for?

**Comment by hmitsch** [comment]
Hi @m-branson,

thanks for flagging this. Definitely relevant.

Short answer: No, we have probably not accounted for this.
Long answer: This is part of a bigger, more complex topic that is not solved yet.

I suggest to put this to the icebox until we have a solution for the so called "high volume, minimal engagement authentication" use cases.

Best regards,
   Henrik

**Comment by mbransn** [comment]
Sounds good @hmitsch ...moved to icebox and we'll track as we work through high volume, minimal engagement auth use cases.

**Comment by hmitsch** [comment]
Linking to https://github.com/mozilla/thimble.mozilla.org/issues/2431 because these two conversations are somehow/remotely related.
