### ISSUE TITLE
Fix workaround for adding new emails to be compatible with SSO dashboard.

### ISSUE THREAD

**Issue by johngian** [mozilla-iam/iam-project-backlog#65]
This ticket refers to an issue when adding alternate emails to mozillians.org that might conflict with the SSO dashboard.

* If you are already authenticated in mozillians.org and start a new OIDC authentication flow we identify it as an attempt to add a new email.
* Also most of the times this will raise an error because email exists in our database.

**Comment by andrewkrug** [comment]
@johngian can you clarify this story... this card keeps coming up in my list.  I know we discussed it yesterday but I'm not clear on the work item.

**Comment by andrewkrug** [comment]
@hmitsch can you clarify this story.  I'm sending a bump on this to see if we need it as part of this sprint and if there's something I need to do on the issue.

**Comment by hmitsch** [comment]
ACK.
/cc @johngian

**Comment by johngian** [comment]
I think that we should remove ``[AUTH0 DASHBOARD]`` and change it to ``mozillians``. This ticket refers to an issue when adding alternate emails to mozillians.org that might conflict with the SSO dashboard.

* If you are already authenticated in mozillians.org and start a new OIDC authentication flow we identify it as an attempt to add a new email.
* Also most of the times this will raise an error because email exists in our database.

**Comment by andrewkrug** [comment]
@hmitsch for sprint #5 let's clarify this.  Some of the work for the new user profile accommodates multiple e-mails.
