### ISSUE TITLE
Production Deployment of SSO Dashboard

### ISSUE THREAD

**Issue by andrewkrug** [mozilla-iam/iam-project-backlog#78]
Deploy the new dashboard to sso.mozilla.org with the new configuration and link back to okta dashboard.

**Comment by andrewkrug** [comment]
It was decided yesterday that we will put "production" at sso.security.mozilla.org until such time as we are ready to move over to sso.mozilla.org.  Production should include an HA deployment of the dashboard design as well.  

There will be two testing phases for user acceptance.  

- Phase 1 : IAM Team only (Alpha test)
- Phase 2 : IAM Team + Key players in IT (Sylvie, et all)

**Comment by andrewkrug** [comment]
@jdow what are the criteria that you think need to be completed to move over to the new dashboard to replace current okta dash?

**Comment by jdow** [comment]
I think the main criteria is user acceptance and decent UI. I think functionally what we have today is sufficient.

**Comment by andrewkrug** [comment]
Cool then we're only really waiting on two things... both of which are on my to-do for this week:

- [ ] Restructure credstash secrets to match new style and naming
- [x] Move SSL certs to production let's encrypt server and store in credstash.

**Comment by andrewkrug** [comment]
SSL certs moved to ACM certificates today in preparation for productionalization.

**Comment by andrewkrug** [comment]
This will likely complete tomorrow and have a CI pipeline as well re: sso.security.allizom.org as our temporary production until we switch over.

**Comment by andrewkrug** [comment]
Production deploy in place.  Waiting DNS transition in bugzilla bug https://bugzilla.mozilla.org/show_bug.cgi?id=1359243

**Comment by tyearns** [comment]
Shall we rename this story Phase 2, and make reference to the remaining open issues at: https://github.com/mozilla-iam/sso-dashboard/issues

**Comment by gdestuynder** [comment]
this is done ;-)
sso.mozilla.com
