### ISSUE TITLE
Mozillians.org Mapbox Integration

### ISSUE THREAD

**Issue by hmitsch** [mozilla-iam/iam-project-backlog#8]
Acceptance criteria:
* Registered users can change their location in their Mozillians.org profile
* New users can register and provide their location information
* Users who registered during the "deactivated map" period get an email to update their location from 0;0 to something meaningful

**Comment by mbransn** [comment]
Following the Mozillians UI meeting between Henrik, Tasos, Nikos and myself -- I will update the Mozillians wireframes to incorporate city, state/region and country fields on sign up. 

Our approach will be iterative and we have decided that a round of user testing will be done on a later sprint to determine if utilizing a map visual (for sign up and in the user settings page) is a viable addition to the user experience.

**Comment by akatsoulas** [comment]
For the first iteration, the user will be able to submit location data through three drop-down menus which will provide sanitized data for countries, cities and regions. Ideally, the choices of each field will be dependent on the choice of the previous field. Eg country -> region (if applicable) -> city. These fields will support auto-completion.

Questions to answer:
* Are we keeping the current geolocation dataset?
* Are we going to have a data migration?
    - How are we going to address naming conflicts? 
* Do we need lat/lon coordinates?
* Are we redesigning the db schema?

Planning:
Plan the iterations of the geolocation app in mozillians.org

**Comment by mbransn** [comment]
@akatsoulas @johngian @comzeradd @hmitsch :

Attached is the IAM wireframe Sketch file (currently Mozillians focused). Comps for both mobile and desktop versions of the proposed log in/sign up flow are included. I've added an annotation above each screen outlining where I believe it 'lives'...within the Auth0 Lock or decentralized at the RP level (in this case, Mozillians). See attached screen shot for clarity.

Clickable prototype link will be available tomorrow (2/14) for both mobile and desktop.

Immediate questions:

- Does this meet technical needs for updating current location at the Mozillians sign up level?
- Are these screens annotated accurately re: located in the Lock vs. RP?
- Would you like to have a call/vid tomorrow (Tues) morning to discuss anything further before I'm offline Wed-Thurs?

[MOZ_IAM_Auth0.sketch.zip](https://github.com/mozilla/iam-project-backlog/files/770940/MOZ_IAM_Auth0.sketch.zip)

<img width="927" alt="lock-annotation" src="https://cloud.githubusercontent.com/assets/18686986/22882629/fde4a9e2-f1e3-11e6-9590-c45310d5d4bc.png">

**Comment by a-kilroy** [comment]
Please include me on any UX call. Thanks!

**Comment by mbransn** [comment]
Sketch Cloud link: https://sketch.cloud/s/my87

**Note:** This does not show document annotation and reorders pages, pulling them out of accurate user flow order. Recommend downloading [Sketch](https://www.sketchapp.com/) app and viewing actual file (updated version below).

Clickable prototypes will be available today.

[MOZ_IAM_Auth0.sketch.zip](https://github.com/mozilla/iam-project-backlog/files/773424/MOZ_IAM_Auth0.sketch.zip)

**Comment by mbransn** [comment]
**Desktop Prototype:** http://bit.ly/2kF7XtO

**Note:** Toggle 'Comments' in the bottom right hand corner to view/respond/leave notes on a respective screen.

**Comment by mbransn** [comment]
Members from the ParSys team met today to review the current Mozillians desktop prototype (wireframe), focus was on the ‘Sign Up’ flow. 

**Various updates were noted:**
- User name is a required field (resolved in new iteration)
- Password is not a field for sign up to mozillians. LDAP users will already have a password. (resolved in new iteration)
- Sign Up email success message lives within Auth0 Lock, not at the RP. (resolved in new iteration)
- reCAPTCHA will open a dialog box when checkbox is selected. We will move forward with baseline implementation & styling, iterating on design at a later sprint. (annotated in ‘comments’ of desktop prototype)
- Mozilla Newsletter opt in added to sign up form. Selecting checkbox will reveal further options: language dropdown and an html or text radio button. We will iterate further on functionality and design at a later sprint. (annotated in the ‘comments’ of desktop prototype)

**Question that was surfaced:** When design of the UI is initiated, will we start with the Auth0 Lock or the de-centralized Sign Up flow (located on the RP)? 
_General consensus was to start with the Auth0 Lock, considering its potential limitations and the potential long term goal of centralizing Sign Up with Log In. More discussion will be had before UI design is initiated._

*@akatsoulas @johngian @comzeradd:* 
- Please review the updated desktop prototype and new mobile prototype (links below). 
- Leave comments if/where needed. 
- If a screen lives in a location other than how it is annotated (Auth0 Lock vs RP) please call it out now so we can resolve any potential confusion.

**Desktop Prototype:** http://bit.ly/2kF7XtO
_Contains annotation in 'comments' mode._

**Mobile Prototype:** http://bit.ly/2lL8o5X 
_Possible to view on desktop as well as on mobile device._

**Sketch Cloud:** https://sketch.cloud/s/my87 
_Note that these flat comps are out of order, utilize prototypes above to view user flow. Sketch file attached below._

[MOZ_IAM_Auth0.sketch.zip](https://github.com/mozilla/iam-project-backlog/files/774060/MOZ_IAM_Auth0.sketch.zip)

**Comment by seanatmoz** [comment]
Mozilla IT subscribes to Mapbox and Maxmind for geo location. If Mapbox doesn't work, maybe look at Maxmind (https://www.maxmind.com/en/geoip2-databases)? I think we subscribe to country/city only but I could be wrong. Matt Pressman might know better.
