### ISSUE TITLE
Create Cloudformation to Deploy Multi-Region sso.dashboard

### ISSUE THREAD

**Issue by andrewkrug** [mozilla-iam/iam-project-backlog#83]
SSO dashboard now has valid SSL certificates in 3 regions in both dev and prod infosec accounts.  Let's move to deploying this with CF as a part of the applications maturity model.

**Comment by andrewkrug** [comment]
First re-deploy of sso.allizom.org with load balancing is complete.

**Comment by andrewkrug** [comment]
Dev version  complete for us-west-2

**Comment by andrewkrug** [comment]
Prod version complete in us-west-2

**Comment by tyearns** [comment]
Current status?

**Comment by andrewkrug** [comment]
Same as 3 days ago.  "Prod version complete in us-west-2"  We'll launch in us-west-2 and grow out to 3 regions.  This needs to stay open and roll over into the next sprint of work.

**Comment by tyearns** [comment]
Got it.

**Comment by andrewkrug** [comment]
This has been broken apart into region specific and roles.
