### ISSUE TITLE
Vanity urls served by sso.mozilla.com

### ISSUE THREAD

**Issue by andrewkrug** [mozilla-iam/iam-project-backlog#84]
@jdow informs me that there is either an instance of nginx or apache on sso.mozilla.com that currently handles all the redirects to big long sso URLs.  We'll need to account for this feature and build it into the dashboard design in some way or stage a new service for handling sso vanity URLs.

**Comment by andrewkrug** [comment]
@jdow @jeffbryner can you close this one out if you think that this feature is ready

**Comment by jeffbryner** [comment]
Nicely done!
