### ISSUE TITLE
(Infra Mig) Mozillians.org infrastructure migration

### ISSUE THREAD

**Issue by hmitsch** [mozilla-iam/iam-project-backlog#9]
TBD

**Comment by gdestuynder** [comment]
@flamingspaz is this still used as a tracker or should this be closed (if theres another tracker just refer to it and close, or if its done just close)

**Comment by flamingspaz** [comment]
Sprint 10 goal was the tracker for this https://github.com/mozilla-iam/iam-project-backlog/issues/159
