### ISSUE TITLE
Penetration test (pentest) of Mozillians.org

### ISSUE THREAD

**Issue by hmitsch** [mozilla-iam/iam-project-backlog#94]
---------- Forwarded message ----------
From: Henrik Mitsch <hmitsch@mozilla.com>
Date: Fri, Apr 7, 2017 at 7:50 PM
Subject: Re: Q2 Pentest of Mozillians.org?
To: Jonathan Claudius <jclaudius@mozilla.com>
Cc: John Giannelos <nemo@mozilla.com>, Tasos Katsoulas <akatsoulas@mozilla.com>, Yousef Alam <yalam@mozilla.com>

yes, awesome. We are totally in for that. 

On Fri, 7 Apr 2017 at 16:24, Jonathan Claudius <jclaudius@mozilla.com> wrote:

    Henrik,

    Over the past 3 quarters the Enterprise Information Security team has selected 3 critical services each quarter to perform a more in-depth security assessment ("a penetration test" or "pentest") in and effort to identify security weaknesses in those services.  By knowing about these weaknesses, the hope is that we can call those out and fix them before an attacker can abuse them.

    I'm reaching out to you because I'm being told by my peers (jabba/weir/kang/jeff) that mozillians.org is going to be playing a much bigger role from an IAM standpoint soon and I wanted to gauge your interest in such a test for Q2.

    What would I need from you?

    - An acknowledgement that you're interested in doing the test in Q2
    - A hour of your time so we could conduct a scoping call and figure out what would be tested
    - A point of contact for questions when/if they come up during the test (this is often to help with context about whether an issue is truly an issue or not)

    What would you receive in return?

    - Bug/Issue reports, which describe specific security issues we identify with the service, issues would be filed as they are discovered.
    - A written report that consolidates all the issues, delivered at the end of the quarter.
    - A greater confidence that there are less unknown security issues with the service.

    If you could let me know in the next couple business days whether this is something you're willing to have done, that would be very helpful so I get the process started or identify an alternate service for Q2.

    Thanks,

    -Jonathan

**Comment by claudijd** [comment]
👍

**Comment by gdestuynder** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1357743 this is the pentest bug

**Comment by gdestuynder** [comment]
as per above test this is done, remediations are tracked there
