### ISSUE TITLE
Referrer policy for Mozillians.org

### ISSUE THREAD

**Issue by hmitsch** [mozilla-iam/iam-project-backlog#95]
---------- Forwarded message ----------
From: Richard Soderberg <rsoderberg@mozilla.com>
Date: Mon, Apr 10, 2017 at 7:00 PM
Subject: Re: [mozilla/iam-project-backlog] Enable HSTS preloading in mozillians.org (#81)
To: Henrik Mitsch <hmitsch@mozilla.com>

Could you open a new issue about adding a Referrer policy to Mozillians.org? I found Phonebook leading search terms to offsites at one point, so now we have a more strict policy. (You're welcome to steal mine, it's set on all responses post-SSO.)

 - R.

**Comment by hmitsch** [comment]
From @johngian:
> Here is the header Richard is talking about:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy

**Comment by floatingatoll** [comment]
cc @april since this will end up being replacement Phonebook's referrer-policy header someday.

**Comment by april** [comment]
Ahh, thanks for pulling me in.  Let me know if you need any help with things!

**Comment by gdestuynder** [comment]
@johngian im guessing this is done right?
