### ISSUE TITLE
SSO Dashboard New App Access Request - UI Design

### ISSUE THREAD

**Issue by mbransn** [mozilla-iam/iam-project-backlog#97]
Moving this task to its own issue (from #53) as it will be implemented during a later release date, currently TBD.

-----

Design UI that allows a user to request access to a new app from the Auth0 SSO Dashboard, [user stories for reference](https://docs.google.com/a/mozilla.com/document/d/1xZaDKYcZGT9rMZfWtqWFek9onnXVPZOiRq8SUlgaGkw/edit?usp=sharing). 

- [ ] define plan and rewrite this checkbox

**Comment by andrewkrug** [comment]
@jdow should this be an integration with service now?

**Comment by jdow** [comment]
I think it's probably going to be as it is now: either servicenow or bugzilla bug to request access to an app, or to request addition to a group in general. I think long term each app would have a group associated with it and those groups would likely be managed by IT or self-serve group owners in mozillians.org, etc. I don't know that we'd need a specific UI for requesting access, other than maybe a link at the bottom "Not seeing the app you need? Click here to open a ticket" type of thing.

**Comment by mbransn** [comment]
Thanks for the details here @jdow ... the new UI has this living in the menu as an actionable UI element (see menu image below). This 'feels' like a primary level action similar to settings and log out, where as help desk/privacy/legal are secondary level actions that live in the footer.

Thinking that 'access request' in the menu will direct to a form that has an intro with the language you used plus a little bit more, something like: "Need access to an app or not seeing the app you need? Request app or group access using the form below." And secondary messaging: "Not sure what you need? Reach out to the help desk." with and inline help desk link.

Form fields being:
- user email
- 'single app' or 'group access' selector (defaults to single app)
- name of app or group (this is a drop down populated based on the app or group selector)
- do we need a comments field?
- do we need any other verifying information or does their email tell you what you need to know?
- submit button
- success message w/button to return to SSO dashboard

Thoughts on this approach @andrewkrug @jdow?

![menu-active](https://cloud.githubusercontent.com/assets/18686986/25050640/7c70d8ec-20fd-11e7-9331-150c5065dbdb.png)

**Comment by gdestuynder** [comment]
we want this, likely Q12018

**Comment by gdestuynder** [comment]
Deferred
