### ISSUE TITLE
SSO Dashboard Favorite Apps - UI Design

### ISSUE THREAD

**Issue by mbransn** [mozilla-iam/iam-project-backlog#98]
Moving this task to its own issue (from #53) as it will be implemented during a later release date, currently TBD.

-----

Design UI that allows users to add/remove apps as Favorites within the Auth0 SSO Dashboard. This includes UI for a Favorites section.

[User stories](https://docs.google.com/a/mozilla.com/document/d/1xZaDKYcZGT9rMZfWtqWFek9onnXVPZOiRq8SUlgaGkw/edit?usp=sharing) for reference.

**Comment by gdestuynder** [comment]
Currently leaving in icebox, though this might happen after Q4O4_CoherentUx
